### ISSUE TITLE
Documentation ?

### ISSUE THREAD

**Issue by Snowbaha** [answear/dpd-pl-pickup-services-bundle#4]
Hello,

Do you have a documentation "how it work?"
Is it working with France FR DPD ?

Regards

**Comment by malarzm** [comment]
We will update the README file hopefully today :) 

As for DPD FR you'd need to check with them whether their pickup points are available through https://mypudo.dpd.com.pl/api/pudo service. FWIW I wasn't able to fetch any using `FRA` as a country code

**Comment by Snowbaha** [comment]
Cool, I will wait for it to test if it's possible in my case^^

The french example use this one:

`
// Webservice call
        $mypudo         = file_get_contents('http://mypudo.pickup-services.com/mypudo/mypudo.asmx/GetPudoList?carrier=EXA&key=deecd7bc81b71fcc0e292b53e826c48f&address='.urlencode($address).'&zipCode='.urlencode($zipcode).'&city='.urlencode($city).'&countrycode=fr&requestID=0&date_from='.urlencode($date).'&max_pudo_number=&max_distance_search=&weight=&category=&holiday_tolerant=');
        $xml            = new SimpleXMLElement($mypudo);
        $relais_items   = $xml->PUDO_ITEMS;
`

**Comment by malarzm** [comment]
At a glance the urls are different, but that's something we could work around using settings. The most important is whether the XML structure is the same for both services, you can check the one supported by bundle here: https://github.com/answear/dpd-pl-pickup-services-bundle/blob/master/tests/fixtures/full_pudo.xml

**Comment by Snowbaha** [comment]
It looks to be the same as their example: 
![image](https://user-images.githubusercontent.com/3284722/116551895-b19acc80-a8f8-11eb-9779-f62ef1bc2fde.png)

**Comment by malarzm** [comment]
The README is updated now. The best way forward for you would be to "hack" API endpoints defined in https://github.com/answear/dpd-pl-pickup-services-bundle/blob/bb295d52a5a4afd59fce9931a0f3f74b3da5162f/src/Service/PUDOList.php and see if the library is indeed able to parse XML's provided by DPD FR. If it is we will make it possible to have the endpoints configurable :)

**Comment by Snowbaha** [comment]
Ok thank you :)
